package com.excavplayer.domain.model

data class UserSettings(
    val defaultPlaybackSpeed: Float = 1.0f,
    val autoResume: Boolean = true,
    val resumeThresholdPercent: Float = 0.95f,
    val defaultRepeatMode: RepeatMode = RepeatMode.OFF,
    val autoplayNextVideo: Boolean = true,
    val subtitlesEnabled: Boolean = true,
    val preferredSubtitleLanguage: String? = "English",
    val preferredAudioLanguage: String? = null,
    val gestureControlsEnabled: Boolean = true,
    val brightnessGestureEnabled: Boolean = true,
    val volumeGestureEnabled: Boolean = true,
    val subtitleTextSize: String = "Normal",
    val subtitleTextColor: String = "White",
    val subtitleBackgroundStyle: String = "Outline",
    val rememberVolume: Boolean = true,
    val continueWatchingEnabled: Boolean = true,
    val defaultScreenOrientation: String = "Auto",
    val defaultMediaFit: String = "Fit to Screen",
    val lastOpenedFolder: String? = null,
    val subtitleVerticalPositionPercent: Float = 0.90f,
    val autoRescanOnLaunch: Boolean = true,
    val headsetDetectionEnabled: Boolean = true,
    val stopOnScreenOff: Boolean = true,
    val hardwareAccelerationMode: String = "Automatic",
    val hardwareAccelerationEnabled: Boolean = true,
    val dialogueBoostEnabled: Boolean = false,
    val matchDisplayRefreshRate: Boolean = false
)
